name: shrawan_portfolio_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  camera: ^0.10.5+9
  record: ^5.0.4
  audioplayers: ^5.2.1
  flutter_pdfview: ^1.3.2
  webview_flutter: ^4.7.0
  intl: ^0.19.0
  google_fonts: ^6.1.0
  font_awesome_flutter: ^11.0.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/alg_express/
    - assets/asha_connect/
    - assets/bca_guide_nepal/
    - assets/chotkari/
    - assets/eps_topik/
    - assets/ipo_connect/
    - assets/jhigu_store/
    - assets/medipuzzle/
    - assets/name_online/
    - assets/uhub/
    - assets/yds/